-- ==========================================
-- ELIMINACIÓN PREVIA DE TABLAS Y CONSTRAINTS
-- ==========================================

ALTER TABLE ROL DROP PRIMARY KEY CASCADE;
ALTER TABLE USUARIO DROP PRIMARY KEY CASCADE;
ALTER TABLE TIPODOCUMENTO DROP PRIMARY KEY CASCADE;
ALTER TABLE DOCUMENTO DROP PRIMARY KEY CASCADE;
ALTER TABLE AUTOR DROP PRIMARY KEY CASCADE;
ALTER TABLE EDITORIAL DROP PRIMARY KEY CASCADE;
ALTER TABLE DOCUMENTO_AUTOR DROP PRIMARY KEY CASCADE;
ALTER TABLE DOCUMENTO_EDITORIAL DROP PRIMARY KEY CASCADE;
ALTER TABLE SOLICITUD DROP PRIMARY KEY CASCADE;
ALTER TABLE SOLICITUD_DETALLE DROP PRIMARY KEY CASCADE;

DROP TABLE SOLICITUD_DETALLE CASCADE CONSTRAINTS;
DROP TABLE SOLICITUD CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTO_EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTO_AUTOR CASCADE CONSTRAINTS;
DROP TABLE EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE DOCUMENTO CASCADE CONSTRAINTS;
DROP TABLE TIPODOCUMENTO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE ROL CASCADE CONSTRAINTS;

-- ===============================
-- CREACIÓN DE TABLAS PRINCIPALES
-- ===============================

CREATE TABLE ROL
(
  ID_ROL NUMBER,
  NOMBRE_ROL VARCHAR2(50 BYTE),
  DIAS_PRESTAMO NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE USUARIO
(
  ID_USUARIO NUMBER,
  NOMBRE VARCHAR2(100 BYTE),
  APELLIDO VARCHAR2(100 BYTE),
  NOMBRE_USUARIO VARCHAR2(50 BYTE),
  CONTRASENA VARCHAR2(255 BYTE),
  CORREO_RECUPERACION VARCHAR2(100 BYTE),
  ID_ROL NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE TIPODOCUMENTO
(
  ID_TIPO NUMBER,
  NOMBRE_TIPO VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE DOCUMENTO
(
  ID_DOCUMENTO NUMBER,
  TITULO VARCHAR2(200 BYTE),
  FORMATO VARCHAR2(10 BYTE),
  ID_TIPO NUMBER,
  DISPONIBLE CHAR(1 BYTE) DEFAULT 'S' CHECK (DISPONIBLE IN ('S','N')),
  UBICACION_FISICA VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE AUTOR
(
  ID_AUTOR NUMBER,
  NOMBRE_AUTOR VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE EDITORIAL
(
  ID_EDITORIAL NUMBER,
  NOMBRE_EDITORIAL VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE DOCUMENTO_AUTOR
(
  ID_DOCUMENTO NUMBER,
  ID_AUTOR NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE DOCUMENTO_EDITORIAL
(
  ID_DOCUMENTO NUMBER,
  ID_EDITORIAL NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SOLICITUD
(
  ID_SOLICITUD NUMBER,
  ID_USUARIO NUMBER,
  FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_DEVOLUCION TIMESTAMP,
  ESTADO VARCHAR2(20 BYTE) DEFAULT 'Pendiente'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE SOLICITUD_DETALLE
(
  ID_SOLICITUD NUMBER,
  ID_DOCUMENTO NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

-- =============================
-- PRIMARY KEYS Y CONSTRAINTS
-- =============================

ALTER TABLE ROL ADD (
  CONSTRAINT ROL_PK
  PRIMARY KEY (ID_ROL)
);

ALTER TABLE USUARIO ADD (
  CONSTRAINT USUARIO_PK
  PRIMARY KEY (ID_USUARIO)
);

ALTER TABLE TIPODOCUMENTO ADD (
  CONSTRAINT TIPODOCUMENTO_PK
  PRIMARY KEY (ID_TIPO)
);

ALTER TABLE DOCUMENTO ADD (
  CONSTRAINT DOCUMENTO_PK
  PRIMARY KEY (ID_DOCUMENTO)
);

ALTER TABLE AUTOR ADD (
  CONSTRAINT AUTOR_PK
  PRIMARY KEY (ID_AUTOR)
);

ALTER TABLE EDITORIAL ADD (
  CONSTRAINT EDITORIAL_PK
  PRIMARY KEY (ID_EDITORIAL)
);

ALTER TABLE DOCUMENTO_AUTOR ADD (
  CONSTRAINT DOCUMENTO_AUTOR_PK
  PRIMARY KEY (ID_DOCUMENTO, ID_AUTOR)
);

ALTER TABLE DOCUMENTO_EDITORIAL ADD (
  CONSTRAINT DOCUMENTO_EDITORIAL_PK
  PRIMARY KEY (ID_DOCUMENTO, ID_EDITORIAL)
);

ALTER TABLE SOLICITUD ADD (
  CONSTRAINT SOLICITUD_PK
  PRIMARY KEY (ID_SOLICITUD)
);

ALTER TABLE SOLICITUD_DETALLE ADD (
  CONSTRAINT SOLICITUD_DETALLE_PK
  PRIMARY KEY (ID_SOLICITUD, ID_DOCUMENTO)
);

-- =============================
-- FOREIGN KEYS
-- =============================

ALTER TABLE USUARIO ADD (
  CONSTRAINT USUARIO_R01 
  FOREIGN KEY (ID_ROL) 
  REFERENCES ROL (ID_ROL)
  ON DELETE CASCADE
);

ALTER TABLE DOCUMENTO ADD (
  CONSTRAINT DOCUMENTO_R01 
  FOREIGN KEY (ID_TIPO)
  REFERENCES TIPODOCUMENTO (ID_TIPO)
  ON DELETE SET NULL
);

ALTER TABLE DOCUMENTO_AUTOR ADD (
  CONSTRAINT DOCUMENTO_AUTOR_R01 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
  ON DELETE CASCADE
);

ALTER TABLE DOCUMENTO_AUTOR ADD (
  CONSTRAINT DOCUMENTO_AUTOR_R02 
  FOREIGN KEY (ID_AUTOR)
  REFERENCES AUTOR (ID_AUTOR)
  ON DELETE CASCADE
);

ALTER TABLE DOCUMENTO_EDITORIAL ADD (
  CONSTRAINT DOCUMENTO_EDITORIAL_R01 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
  ON DELETE CASCADE
);

ALTER TABLE DOCUMENTO_EDITORIAL ADD (
  CONSTRAINT DOCUMENTO_EDITORIAL_R02 
  FOREIGN KEY (ID_EDITORIAL)
  REFERENCES EDITORIAL (ID_EDITORIAL)
  ON DELETE CASCADE
);

ALTER TABLE SOLICITUD ADD (
  CONSTRAINT SOLICITUD_R01 
  FOREIGN KEY (ID_USUARIO)
  REFERENCES USUARIO (ID_USUARIO)
  ON DELETE CASCADE
);

ALTER TABLE SOLICITUD_DETALLE ADD (
  CONSTRAINT SOLICITUD_DETALLE_R01 
  FOREIGN KEY (ID_SOLICITUD)
  REFERENCES SOLICITUD (ID_SOLICITUD)
  ON DELETE CASCADE
);

ALTER TABLE SOLICITUD_DETALLE ADD (
  CONSTRAINT SOLICITUD_DETALLE_R02 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
);