-- ==========================================
-- ELIMINACIÓN PREVIA DE TABLAS Y CONSTRAINTS
-- ==========================================
ALTER TABLE IF EXISTS ROL DROP CONSTRAINT IF EXISTS ROL_PK CASCADE;
ALTER TABLE IF EXISTS USUARIO DROP CONSTRAINT IF EXISTS USUARIO_PK CASCADE;
ALTER TABLE IF EXISTS TIPODOCUMENTO DROP CONSTRAINT IF EXISTS TIPODOCUMENTO_PK CASCADE;
ALTER TABLE IF EXISTS DOCUMENTO DROP CONSTRAINT IF EXISTS DOCUMENTO_PK CASCADE;
ALTER TABLE IF EXISTS AUTOR DROP CONSTRAINT IF EXISTS AUTOR_PK CASCADE;
ALTER TABLE IF EXISTS EDITORIAL DROP CONSTRAINT IF EXISTS EDITORIAL_PK CASCADE;
ALTER TABLE IF EXISTS DOCUMENTO_AUTOR DROP CONSTRAINT IF EXISTS DOCUMENTO_AUTOR_PK CASCADE;
ALTER TABLE IF EXISTS DOCUMENTO_EDITORIAL DROP CONSTRAINT IF EXISTS DOCUMENTO_EDITORIAL_PK CASCADE;
ALTER TABLE IF EXISTS SOLICITUD DROP CONSTRAINT IF EXISTS SOLICITUD_PK CASCADE;
ALTER TABLE IF EXISTS SOLICITUD_DETALLE DROP CONSTRAINT IF EXISTS SOLICITUD_DETALLE_PK CASCADE;

DROP TABLE IF EXISTS SOLICITUD_DETALLE CASCADE;
DROP TABLE IF EXISTS SOLICITUD CASCADE;
DROP TABLE IF EXISTS DOCUMENTO_EDITORIAL CASCADE;
DROP TABLE IF EXISTS DOCUMENTO_AUTOR CASCADE;
DROP TABLE IF EXISTS EDITORIAL CASCADE;
DROP TABLE IF EXISTS AUTOR CASCADE;
DROP TABLE IF EXISTS DOCUMENTO CASCADE;
DROP TABLE IF EXISTS TIPODOCUMENTO CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS ROL CASCADE;

-- ===============================
-- CREACIÓN DE TABLAS PRINCIPALES
-- ===============================

CREATE TABLE ROL
(
  ID_ROL SERIAL,
  NOMBRE_ROL VARCHAR(50),
  DIAS_PRESTAMO INT
);

CREATE TABLE USUARIO
(
  ID_USUARIO SERIAL,
  NOMBRE VARCHAR(100),
  APELLIDO VARCHAR(100),
  NOMBRE_USUARIO VARCHAR(50),
  CONTRASEÑA VARCHAR(255),
  CORREO_RECUPERACION VARCHAR(100),
  ID_ROL INT
);

CREATE TABLE TIPODOCUMENTO
(
  ID_TIPO SERIAL,
  NOMBRE_TIPO VARCHAR(50)
);

CREATE TABLE DOCUMENTO
(
  ID_DOCUMENTO SERIAL,
  TITULO VARCHAR(200),
  FORMATO VARCHAR(10) CHECK (FORMATO IN ('Digital', 'Fisico')),
  ID_TIPO INT,
  DISPONIBLE BOOLEAN DEFAULT TRUE,
  UBICACION_FISICA VARCHAR(200)
);

CREATE TABLE AUTOR
(
  ID_AUTOR SERIAL,
  NOMBRE_AUTOR VARCHAR(100)
);

CREATE TABLE EDITORIAL
(
  ID_EDITORIAL SERIAL,
  NOMBRE_EDITORIAL VARCHAR(100)
);

CREATE TABLE DOCUMENTO_AUTOR
(
  ID_DOCUMENTO INT,
  ID_AUTOR INT
);

CREATE TABLE DOCUMENTO_EDITORIAL
(
  ID_DOCUMENTO INT,
  ID_EDITORIAL INT
);

CREATE TABLE SOLICITUD
(
  ID_SOLICITUD SERIAL,
  ID_USUARIO INT,
  FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_DEVOLUCION TIMESTAMP,
  ESTADO VARCHAR(20) DEFAULT 'Pendiente'
);

CREATE TABLE SOLICITUD_DETALLE
(
  ID_SOLICITUD INT,
  ID_DOCUMENTO INT
);

-- =============================
-- PRIMARY KEYS Y CONSTRAINTS
-- =============================

ALTER TABLE ROL 
ADD CONSTRAINT ROL_PK
PRIMARY KEY (ID_ROL);

ALTER TABLE USUARIO 
ADD CONSTRAINT USUARIO_PK
PRIMARY KEY (ID_USUARIO);

ALTER TABLE TIPODOCUMENTO 
ADD CONSTRAINT TIPODOCUMENTO_PK
PRIMARY KEY (ID_TIPO);

ALTER TABLE DOCUMENTO 
ADD CONSTRAINT DOCUMENTO_PK
PRIMARY KEY (ID_DOCUMENTO);

ALTER TABLE AUTOR 
ADD CONSTRAINT AUTOR_PK
PRIMARY KEY (ID_AUTOR);

ALTER TABLE EDITORIAL 
ADD CONSTRAINT EDITORIAL_PK
PRIMARY KEY (ID_EDITORIAL);

ALTER TABLE DOCUMENTO_AUTOR 
ADD CONSTRAINT DOCUMENTO_AUTOR_PK
PRIMARY KEY (ID_DOCUMENTO, ID_AUTOR);

ALTER TABLE DOCUMENTO_EDITORIAL 
ADD CONSTRAINT DOCUMENTO_EDITORIAL_PK
PRIMARY KEY (ID_DOCUMENTO, ID_EDITORIAL);

ALTER TABLE SOLICITUD 
ADD CONSTRAINT SOLICITUD_PK
PRIMARY KEY (ID_SOLICITUD);

ALTER TABLE SOLICITUD_DETALLE 
ADD CONSTRAINT SOLICITUD_DETALLE_PK
PRIMARY KEY (ID_SOLICITUD, ID_DOCUMENTO);

-- =============================
-- FOREIGN KEYS
-- =============================

ALTER TABLE USUARIO 
ADD CONSTRAINT USUARIO_R01 
FOREIGN KEY (ID_ROL) 
REFERENCES ROL (ID_ROL)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE DOCUMENTO ADD
  CONSTRAINT DOCUMENTO_R01 
  FOREIGN KEY (ID_TIPO)
  REFERENCES TIPODOCUMENTO (ID_TIPO)
  ON DELETE SET NULL
  ON UPDATE CASCADE;

ALTER TABLE DOCUMENTO_AUTOR ADD
  CONSTRAINT DOCUMENTO_AUTOR_R01 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
  ON DELETE CASCADE;

ALTER TABLE DOCUMENTO_AUTOR ADD
  CONSTRAINT DOCUMENTO_AUTOR_R02 
  FOREIGN KEY (ID_AUTOR)
  REFERENCES AUTOR (ID_AUTOR)
  ON DELETE CASCADE;

ALTER TABLE DOCUMENTO_EDITORIAL ADD
  CONSTRAINT DOCUMENTO_EDITORIAL_R01 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
  ON DELETE CASCADE;

ALTER TABLE DOCUMENTO_EDITORIAL ADD
  CONSTRAINT DOCUMENTO_EDITORIAL_R02 
  FOREIGN KEY (ID_EDITORIAL)
  REFERENCES EDITORIAL (ID_EDITORIAL)
  ON DELETE CASCADE;

ALTER TABLE SOLICITUD ADD
  CONSTRAINT SOLICITUD_R01 
  FOREIGN KEY (ID_USUARIO)
  REFERENCES USUARIO (ID_USUARIO)
  ON DELETE CASCADE;

ALTER TABLE SOLICITUD_DETALLE ADD
  CONSTRAINT SOLICITUD_DETALLE_R01 
  FOREIGN KEY (ID_SOLICITUD)
  REFERENCES SOLICITUD (ID_SOLICITUD)
  ON DELETE CASCADE;

ALTER TABLE SOLICITUD_DETALLE ADD
  CONSTRAINT SOLICITUD_DETALLE_R02 
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES DOCUMENTO (ID_DOCUMENTO)
  ON DELETE RESTRICT;